### ISSUE TITLE
Runnint `sbt` on windows fails to load the project.

### ISSUE THREAD

**Issue by raulraja** [frees-io/freestyle-examples#4]
```
c:\scala\freestyle-examples>sbt -v
Error: Could not find or load main class #
```
@AdrianRaFo do you think you could test this out in your windows box and see if this is Freestyle related? thanks!

**Comment by AdrianRaFo** [comment]
I have been trying to execute the project in differents ways
I tried to execute directly the TodoListApp.scala but I have an error with `H2TodoItemRepositoryHandler` drop method.
I tried to delete all the not source files and I can load the project but it still shows `no main class detected` and doesn't compile `implicits.scala:92: not found: value ?`
